<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
 - A neuron is a singlenode that takes in input does some calculation and gives an output 
- **Input Layer:**
 - The input layer is the first layer where the data gets fed into the nerualnetwork
- **Hidden Layer:**
 - The hidden layer is the layer in the middle after the input layer. We don't directly access this layer 
- **Output Layer:**
 - The output layer is where we get our answers.
- **Activation:**
 - Activation is determined by passing the output of a node to calculate how on a single node is 
- **Backpropagation:**
 - Back prop is the changing of weights in the best dirrection to minimize the loss function 


## 2. Perceptron on XOR Gates <a id="Q3=2"></a>

Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2|x3|	y|
|---|---|---|---|
1|	1|	1|	1|
1|	0|	1|	0|
0|	1|	1|	0|
0|	0|	1|	0|

In [1]:
class Perceptron(object):
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter

    def fit(self, X, y):
        # weights
        self.weight = np.zeros(1 + X.shape[1])

        # Number of misclassifications
        self.errors = []  # Number of misclassifications

        for i in range(self.niter):
            err = 0
            for xi, target in zip(X, y):
                delta_w = self.rate * (target - self.predict(xi))
                self.weight[1:] += delta_w * xi
                self.weight[0] += delta_w
                err += int(delta_w != 0.0)
            self.errors.append(err)
        return self

    def net_input(self, X):
        return np.dot(X, self.weight[1:]) + self.weight[0]

    def predict(self, X):
        return np.where(self.net_input(X) >= 0.0, 1, 0)

In [2]:
import numpy as np
X = np.array([[1,1,1],
              [1,0,1],
              [0,1,1],
              [0,0,1]])

y = [[1],[0],[0],[0]]

In [3]:
pn = Perceptron()

In [4]:
pn.fit(X, y)

In [5]:
pn.predict(X)

array([1, 0, 0, 0])

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [ ]:
import pandas as pd
heart = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
heart.head()

In [236]:
scalar = StandardScaler()
X_scal = scalar.fit_transform(X)

In [216]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architetecture
        self.inputs = 13
        self.hiddenNodes = 16
        self.outputNodes = 1

        #Initial weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) #3x3
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #3x1

    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))

    def sigmoidPrime(self, s):
        return s * (1 - s)

    def feed_forward(self, X):
        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)

        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)

        return self.activated_output

    def backward(self, X, y, o):
        
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

    
        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error * (self.sigmoidPrime(self.activated_hidden))

        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
         # update the weights:
#         tmp = output_errors * output_network \
#               * (1.0 - output_network)     
#         tmp = self.learning_rate  * np.dot(tmp, 
#                                            output_hidden.T)
#         self.who += tmp
#         # calculate hidden errors:
#         hidden_errors = np.dot(self.who.T, 
#                                output_errors)
#         # update the weights:
#         tmp = hidden_errors * output_hidden * \
#               (1.0 - output_hidden)
#         self.wih += self.learning_rate \
#                           * np.dot(tmp, input_vector.T)
          

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [231]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 13
        self.outputLayerSize = 1
        self.hiddenLayerSize = 8
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single paramater vector.
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize , self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))

In [228]:
from scipy import optimize
class trainer(object):
    def __init__(self, N):
        #Make Local reference to network:
        self.N = N
        
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))   
        
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = self.N.computeGradients(X,y)
        
        return cost, grad
        
    def train(self, X, y):
        #Make an internal variable for the callback function:
        self.X = X
        self.y = y

        #Make empty list to store costs:
        self.J = []
        
        params0 = self.N.getParams()

        options = {'maxiter': 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(X, y), options=options, callback=self.callbackF)

        self.N.setParams(_res.x)
        self.optimizationResults = _res

In [232]:
NN = Neural_Network()
T = trainer(NN)

In [237]:
T.train(X_scal,y)

Optimization terminated successfully.
         Current function value: 3.000002
         Iterations: 112
         Function evaluations: 116
         Gradient evaluations: 116


In [238]:
print("Predicted Output: \n" + str(NN.forward(X))) 
print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss

Predicted Output: 
[[0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 [0.99999755]
 

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: overflow encountered in exp


In [190]:
y[200] - nn.feed_forward(X[200])

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


array([-0.83196746])

In [181]:
np.dot(nn.o_delta[0], nn.weights2)

ValueError: shapes (303,) and (8,1) not aligned: 303 (dim 0) != 8 (dim 0)

In [217]:
nn = NeuralNetwork()

In [125]:
heart.shape

(303, 14)

In [240]:
y = heart['target'].as_matrix()
len(y)

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


303

In [242]:
y =[]
for i in heart['target']:
    y.append([i])

In [168]:
X = heart.drop(columns='target').as_matrix()
X[0]

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([ 63. ,   1. ,   3. , 145. , 233. ,   1. ,   0. , 150. ,   0. ,
         2.3,   0. ,   0. ,   1. ])

numpy.ndarray

In [243]:
for i in range(10000):
    print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X_scal,y)

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


Loss: 
 0.516147156552577
Loss: 
 0.5161478051228321
Loss: 
 0.5161484481134475
Loss: 
 0.5161490855085964
Loss: 
 0.5161497172926364
Loss: 
 0.5161503434501081
Loss: 
 0.5161509639657319
Loss: 
 0.5161515788244071
Loss: 
 0.5161521880112084
Loss: 
 0.5161527915113853
Loss: 
 0.5161533893103587
Loss: 
 0.5161539813937195
Loss: 
 0.5161545677472262
Loss: 
 0.5161551483568029
Loss: 
 0.5161557232085368
Loss: 
 0.5161562922886768
Loss: 
 0.5161568555836303
Loss: 
 0.5161574130799621
Loss: 
 0.5161579647643915
Loss: 
 0.5161585106237901
Loss: 
 0.516159050645181
Loss: 
 0.5161595848157344
Loss: 
 0.5161601131227672
Loss: 
 0.5161606355537404
Loss: 
 0.5161611520962565
Loss: 
 0.5161616627380582
Loss: 
 0.516162167467025
Loss: 
 0.5161626662711727
Loss: 
 0.51616315913865
Loss: 
 0.5161636460577363
Loss: 
 0.516164127016841
Loss: 
 0.5161646020044998
Loss: 
 0.5161650710093731
Loss: 
 0.5161655340202446
Loss: 
 0.5161659910260179
Loss: 
 0.5161664420157158
Loss: 
 0.5161668869784771
Loss: 


In [24]:
heart['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [ ]:
nn.feed_forward(X)

In [31]:
heart['target'][273]

0

In [ ]:
o = nn.feed_forward(X)
o

In [225]:
o = nn.feed_forward(X)
o_error = y - o #error in output
o_delta = o_error * nn.sigmoidPrime(o) # apply derivative of sigmoid to error
print('o_error, this is target minus prpedicted output\n', o_error[0])
print('o_delta, this is o_error times the sigmoid function of output\n', o_delta[0])

z2_error = o_delta.dot(nn.weights2.T) # z2 error: how much our hidden layer weights were off
z2_delta = z2_error*nn.sigmoidPrime(nn.activated_hidden)
print('z2_error, the dot product of the transpose of weigfhts2(hidden layer to output layer)\n', z2_error[0])
print('z2_delta, product of z2_error and the sigmoidPrime of activated_hidden layer\n', z2_delta[0])

print('weights1 first 20\n', nn.weights1[0][:20])
print('weights2 first 20\n', nn.weights2[0][:20])
nn.weights1 += X.T.dot(z2_delta) #Adjust first set (input => hidden) weights
nn.weights2 += nn.activated_hidden.T.dot(o_delta) #adjust second set (hidden => output) weights
print('weights1 updated\n', nn.weights1[0][:20])
print('weights2 updated\n', nn.weights2[0][:20])

o_error, this is target minus prpedicted output
 [1.]
o_delta, this is o_error times the sigmoid function of output
 [3.1645673e-11]
z2_error, the dot product of the transpose of weigfhts2(hidden layer to output layer)
 [ 2.92681872e-11 -1.01251002e-10  2.93352067e-11 -1.19924575e-10
  1.25395192e-11  2.94393459e-11  1.68117580e-11  1.56421772e-11
  2.59796779e-11 -1.11059098e-10 -9.66187096e-11 -1.18200042e-10
  3.14680777e-12 -9.37532857e-11  1.53346611e-11 -1.24272358e-10]
z2_delta, product of z2_error and the sigmoidPrime of activated_hidden layer
 [ 6.73062540e-127 -0.00000000e+000  2.55425897e-236 -0.00000000e+000
  2.43883325e-157  1.47266049e-072  7.92486085e-193  2.09759382e-030
  5.06624014e-250 -0.00000000e+000 -0.00000000e+000 -0.00000000e+000
  1.10595077e-076 -0.00000000e+000  4.83810611e-050 -0.00000000e+000]
weights1 first 20
 [-1.18198919  2.63064076 -1.09830976 -0.3515522  -2.19552051 -0.19936
  0.49422586  0.59309298 -1.30860003 -0.60947099 -1.98165446  0.2990828
 -0

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [104]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier

In [102]:
def create_model():
    model = Sequential()
    model.add(Dense(8, input_dim=13, activation="sigmoid"))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [105]:
model = KerasClassifier(build_fn=create_model, verbose=1)

In [113]:
param_grid = {'batch_size': [8, 16, 32],
              'epochs': [30, 80, 120]}
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

C:\Users\Patrick\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Epoch 1/30
202/202 [==============================] - 1s 6ms/step - loss: 1.0311 - acc: 0.3168
Epoch 2/30
202/202 [==============================] - 0s 163us/step - loss: 0.9241 - acc: 0.3168
Epoch 3/30
202/202 [==============================] - 0s 178us/step - loss: 0.8643 - acc: 0.3168
Epoch 4/30
202/202 [==============================] - 0s 168us/step - loss: 0.8145 - acc: 0.3168
Epoch 5/30
202/202 [==============================] - 0s 193us/step - loss: 0.7749 - acc: 0.3168
Epoch 6/30
202/202 [==============================] - 0s 173us/step - loss: 0.7409 - acc: 0.3168
Epoch 7/30
202/202 [==============================] - 0s 163us/step - loss: 0.7179 - acc: 0.3168
Epoch 8/30
202/202 [==============================] - 0s 163us/step - loss: 0.6986 - acc: 0.3762
Epoch 9/30
202/202 [==============================] - 0s 163us/step - loss: 0.6823 - acc: 0.6782
Epoch 10/30
202/202 [==============================] - 0s 178us/step - loss: 0.6695 - acc: 0.6832
Epoch 11/30
202/202 [==========

In [114]:
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

Best: 0.3498349839409586 using {'batch_size': 8, 'epochs': 120}


In [122]:
grid_result.predict(X)[273]

303/303 [==============================] - 0s 158us/step


array([1], dtype=int64)

In [121]:
y[130:150]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)