# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [2]:
import numpy as np
X = np.array(([0,0,1],
              [0,1,1],
              [1,0,1],
              [0,1,0],
              [1,0,0],
              [1,1,1],
              [0,0,0]))
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [0, 0, 0]])

In [14]:
y = [[0],[1],[1],[1],[1],[0],[0]]
y

[[0], [1], [1], [1], [1], [0], [0]]

In [25]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architetecture
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1

        #Initial weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) #3x3
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #3x1

    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))

    def sigmoidPrime(self, s):
        return s * (1 - s)

    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """

        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)

        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)

        return self.activated_output

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [26]:
nn = NeuralNetwork()

In [27]:
nn.train(X,y)

In [28]:
print('Weights of input to hidden layer\n', nn.weights1)
print('Weights of hidden layer to output\n', nn.weights2)
print('Error\n', nn.o_error)
print('Predicted Output: \n', str(nn.feed_forward(X)))

Weights of input to hidden layer
 [[ 0.31595728 -0.51599277  0.29775516  0.87359247]
 [ 0.42073051 -0.75039658 -0.91340258  3.06564755]
 [ 1.76486291 -1.03908122  2.2384044  -0.39257116]]
Weights of hidden layer to output
 [[0.67411202]
 [0.83005809]
 [0.4089413 ]
 [0.77653473]]
Error
 [[-0.86678948]
 [ 0.09829883]
 [ 0.11602697]
 [ 0.1368531 ]
 [ 0.1406425 ]
 [-0.90451058]
 [-0.83584048]]
Predicted Output: 
 [[0.81382278]
 [0.85498639]
 [0.83241737]
 [0.82232592]
 [0.81497412]
 [0.85749394]
 [0.79328197]]


In [23]:
for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 500 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.66199056]
 [0.67551447]
 [0.70251064]
 [0.70932202]
 [0.73110769]
 [0.70680889]
 [0.69644147]]
Loss: 
 0.2533469402604044
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.64026436]
 [0.65227657]
 [0.67736693]
 [0.68364426]
 [0.70467853]
 [0.68124781]
 [0.67226559]]
Loss: 
 0.24832535340051803
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.62294155]
 [0.6337053 ]
 [0.65706565]
 [0.66244221]
 [0.68278817]
 [0.66059431]
 [0.65231879]]
Loss: 
 0.24518645712733697
+---------EPOCH 4---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [2]:
from mlxtend.data import loadlocal_mnist

X, y = loadlocal_mnist(
        images_path='/Users/Patrick/Desktop/Repos/DS-Unit-4-Sprint-2-Neural-Networks/module2-backpropagation/data/train-images.idx3-ubyte', 
        labels_path='/Users/Patrick/Desktop/Repos/DS-Unit-4-Sprint-2-Neural-Networks/module2-backpropagation/data/train-labels.idx1-ubyte')

In [3]:
train_labels = []
for i in y:
    train_labels.append([i])

In [4]:
import numpy as np
fac = 0.99 / 255

train_imgs = np.asfarray(X[:, :]) * fac + 0.01
train_labels = np.asfarray(y)

In [5]:
train_imgs[0]

array([0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01      ,
       0.01      , 0.01      , 0.01      , 0.01      , 0.01   

In [6]:
train_labels

array([5., 0., 4., ..., 5., 6., 8.])

In [7]:
import pandas as pd 
train_labels_df = pd.read_csv('./data/train_labels.csv', header=None)
train_labels_df.head()

0
0  5
1  0
2  4
3  1
4  9

In [8]:
dummy_labels = pd.get_dummies(train_labels_df[0])
label_matrix = dummy_labels.as_matrix()

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [9]:
df = pd.DataFrame()

In [10]:
dummy_labels.head()

0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  1  0  0  0  0
1  1  0  0  0  0  0  0  0  0  0
2  0  0  0  0  1  0  0  0  0  0
3  0  1  0  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  0  1

In [11]:
for i in dummy_labels.columns:
    dummy_labels[i] = dummy_labels[i].map({0:0.01, 1:0.99})

In [12]:
dummy_labels.head()

0     1     2     3     4     5     6     7     8     9
0  0.01  0.01  0.01  0.01  0.01  0.99  0.01  0.01  0.01  0.01
1  0.99  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01
2  0.01  0.01  0.01  0.01  0.99  0.01  0.01  0.01  0.01  0.01
3  0.01  0.99  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01
4  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.99

In [13]:
label_matrix = dummy_labels.as_matrix()
label_matrix.shape

C:\Users\Patrick\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


(60000, 10)

In [14]:
label_matrix[0]

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.99, 0.01, 0.01, 0.01, 0.01])

In [15]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architetecture
        self.inputs = 784
        self.hiddenNodes = 256
        self.outputNodes = 10

        #Initial weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) #784x16
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #16x10

    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))

    def sigmoidPrime(self, s):
        return s * (1 - s)

    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """

        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)

        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)

        return self.activated_output

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [38]:
nn = NeuralNetwork()

In [ ]:
for i in range(10):
    print('weights2\n', nn.weights2[1])
    print('error\n', str(np.mean(np.square(label_matrix - nn.feed_forward(train_imgs)))))
    nn.train(train_imgs, label_matrix)

In [42]:
nn.train(train_imgs, label_matrix)

In [19]:
str(np.mean(np.square(label_matrix - nn.feed_forward(train_imgs))))

'0.8821000000000008'

In [63]:
o = nn.feed_forward(train_imgs[0])
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
label_matrix[1]

array([0.99, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01])

In [66]:
nn.weights2[0]

array([0.2414308 , 0.5787545 , 0.32720721, 0.10058537, 0.33339977,
       0.6936197 , 0.65226717, 0.99433368, 0.39810497, 0.34569134])

In [37]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architetecture
        self.inputs = 784
        self.hiddenNodes = 256
        self.outputNodes = 10

        #Initial weights
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes) #784x16
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #16x10

    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))

    def sigmoidPrime(self, s):
        return s * (1 - s)

    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """

        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)

        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)

        return self.activated_output

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [39]:
o = nn.feed_forward(train_imgs)
o[0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
o_error = label_matrix - o #error in output
o_delta = o_error * nn.sigmoidPrime(o) # apply derivative of sigmoid to error
print('o_error, this is target minus prpedicted output\n', o_error[0])
print('o_delta, this is o_error times the sigmoid function of output\n', o_delta[0])

z2_error = o_delta.dot(nn.weights2.T) # z2 error: how much our hidden layer weights were off
z2_delta = z2_error*nn.sigmoidPrime(nn.activated_hidden)
print('z2_error, the dot product of the transpose of weigfhts2(hidden layer to output layer)\n', z2_error[0])
print('z2_delta, product of z2_error and the sigmoidPrime of activated_hidden layer\n', z2_delta[0])

print('weights1 first 20\n', nn.weights1[0][:20])
print('weights2 first 20\n', nn.weights2[0][:20])
nn.weights1 += X.T.dot(z2_delta) #Adjust first set (input => hidden) weights
nn.weights2 += nn.activated_hidden.T.dot(o_delta) #adjust second set (hidden => output) weights
print('weights1 updated\n', nn.weights1[0][:20])
print('weights2 updated\n', nn.weights2[0][:20])

o_error, this is target minus prpedicted output
 [-0.99 -0.99 -0.99 -0.99 -0.99 -0.01 -0.99 -0.99 -0.99 -0.99]
o_delta, this is o_error times the sigmoid function of output
 [-0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
z2_error, the dot product of the transpose of weigfhts2(hidden layer to output layer)
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?